name: Cron - EM & TB Pipeline

# Controls when the action will run.
on:
  workflow_dispatch:
  schedule:
    # Automatically run at 9PM every Tuesday and Friday
    - cron:  '0 21 * * 2,5'

jobs:
  scrapeWinningNumbers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          # token: ${{ secrets.FG_PAT }}
          fetch-depth: 0
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Euromillions ETL pipeline
        run: python src/euromillions.py
      - name: Run Thunderball ETL pipeline
        run: python src/thunderball.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.FG_PAT }}
          commit-message: 'ci: bot append new data'
          branch: 'data_set_for_life'
          delete-branch: true
