name: Cron - Lotto & TB Pipeline

# Controls when the action will run.
on:
  workflow_dispatch:
  schedule:
    # Automatically run at 9PM every Wednesday and Saturday
    - cron:  '0 21 * * 3,6'

jobs:
  extractTransformDQ:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          # token: ${{ secrets.FG_PAT }}
          fetch-depth: 0
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Lotto ETL pipeline
        run: python src/lotto.py
      - name: Run Thunderball ETL pipeline
        run: python src/thunderball.py
        
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: Lotto & TB Data Update
          token: ${{ secrets.FG_PAT }}
          commit-message: 'ci: bot append new data'
          branch: 'data_lotto_tb'
          delete-branch: true

      - name: Merge Pull Request
        run: gh pr merge --merge "1"
        env:
          GH_TOKEN: ${{ secrets.FG_PAT }}
